import type { Metadata } from "next";
import { Geist, Geist_Mono, Anton, Comfortaa, Oswald, Outfit, Roboto_Condensed, Sigmar, Teko } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anton = Anton({
  weight: '400',
  variable: '--font-anton',
  subsets: ['latin'],
});

const comfortaa = Comfortaa({
  variable: '--font-comfortaa',
  subsets: ['latin'],
});

const oswald = Oswald({
  variable: '--font-oswald',
  subsets: ['latin'],
});

const outfit = Outfit({
  variable: '--font-outfit',
  subsets: ['latin'],
});

const robotoCondensed = Roboto_Condensed({
  variable: '--font-roboto-condensed',
  subsets: ['latin'],
});

const sigmar = Sigmar({
  weight: '400',
  variable: '--font-sigmar',
  subsets: ['latin'],
});

const teko = Teko({
  variable: '--font-teko',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Financial Advisor Chatbot",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anton.variable} ${comfortaa.variable} ${oswald.variable} ${outfit.variable} ${robotoCondensed.variable} ${sigmar.variable} ${teko.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}